// flow-typed signature: 7040effc5a2a49460a179f76335fae1c
// flow-typed version: <<STUB>>/ali-oss_v4.8.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ali-oss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ali-oss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ali-oss/lib/bucket' {
  declare module.exports: any;
}

declare module 'ali-oss/lib/client' {
  declare module.exports: any;
}

declare module 'ali-oss/lib/cluster' {
  declare module.exports: any;
}

declare module 'ali-oss/lib/image' {
  declare module.exports: any;
}

declare module 'ali-oss/lib/multipart' {
  declare module.exports: any;
}

declare module 'ali-oss/lib/object' {
  declare module.exports: any;
}

declare module 'ali-oss/lib/sts' {
  declare module.exports: any;
}

declare module 'ali-oss/lib/wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ali-oss/lib/bucket.js' {
  declare module.exports: $Exports<'ali-oss/lib/bucket'>;
}
declare module 'ali-oss/lib/client.js' {
  declare module.exports: $Exports<'ali-oss/lib/client'>;
}
declare module 'ali-oss/lib/cluster.js' {
  declare module.exports: $Exports<'ali-oss/lib/cluster'>;
}
declare module 'ali-oss/lib/image.js' {
  declare module.exports: $Exports<'ali-oss/lib/image'>;
}
declare module 'ali-oss/lib/multipart.js' {
  declare module.exports: $Exports<'ali-oss/lib/multipart'>;
}
declare module 'ali-oss/lib/object.js' {
  declare module.exports: $Exports<'ali-oss/lib/object'>;
}
declare module 'ali-oss/lib/sts.js' {
  declare module.exports: $Exports<'ali-oss/lib/sts'>;
}
declare module 'ali-oss/lib/wrapper.js' {
  declare module.exports: $Exports<'ali-oss/lib/wrapper'>;
}
