// flow-typed signature: 4c3f1284121f0986cb1803ef64e1a2ca
// flow-typed version: <<STUB>>/chalk_v1.1.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'chalk/index' {
  declare module.exports: $Exports<'chalk'>;
}
declare module 'chalk/index.js' {
  declare module.exports: $Exports<'chalk'>;
}
