// flow-typed signature: a41930aab80b0eb0ea9744f41d1ad715
// flow-typed version: <<STUB>>/co_v1.2.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'co'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'co' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'co/index' {
  declare module.exports: $Exports<'co'>;
}
declare module 'co/index.js' {
  declare module.exports: $Exports<'co'>;
}
